export const linkClasses =
  "flex items-center gap-2 font-light px-3 py-2 hover:bg-neutral-700 hover:no-underline active:bg-neutral-600 rounded-sm text-base";

export const COLORS = ["#00C49F", "#FFBB28", "#FF8042"];

export const data = [
  {
    name: "Jan",
    Expense: 4000,
    Income: 2400,
  },
  {
    name: "Feb",
    Expense: 3000,
    Income: 1398,
  },
  {
    name: "Mar",
    Expense: 2000,
    Income: 9800,
  },
  {
    name: "Apr",
    Expense: 2780,
    Income: 3908,
  },
  {
    name: "May",
    Expense: 1890,
    Income: 4800,
  },
  {
    name: "Jun",
    Expense: 2390,
    Income: 3800,
  },
  {
    name: "July",
    Expense: 3490,
    Income: 4300,
  },
  {
    name: "Aug",
    Expense: 2000,
    Income: 9800,
  },
  {
    name: "Sep",
    Expense: 2780,
    Income: 3908,
  },
  {
    name: "Oct",
    Expense: 1890,
    Income: 4800,
  },
  {
    name: "Nov",
    Expense: 2390,
    Income: 3800,
  },
  {
    name: "Dec",
    Expense: 3490,
    Income: 4300,
  },
];

export const data1 = [
  { name: "Male", value: 540 },
  { name: "Female", value: 620 },
  { name: "Other", value: 210 },
];

export const recentOrderData = [
  {
    id: "1",
    product_id: "4324",
    customer_id: "23143",
    customer_name: "Shirley A. Lape",
    order_date: "2024-01-17T03:24:00",
    order_total: "₹435.50",
    current_order_status: "PLACED",
    shipment_address: "Bangalore, Karnataka, India",
  },
  {
    id: "7",
    product_id: "7453",
    customer_id: "96453",
    customer_name: "Ryan Carroll",
    order_date: "2024-02-14T05:24:00",
    order_total: "₹96.35",
    current_order_status: "CONFIRMED",
    shipment_address: "Mumbai, Maharashtra, India",
  },
  {
    id: "2",
    product_id: "5434",
    customer_id: "65345",
    customer_name: "Mason Nash",
    order_date: "2024-03-17T07:14:00",
    order_total: "₹836.44",
    current_order_status: "SHIPPED",
    shipment_address: "Delhi, India",
  },
  {
    id: "3",
    product_id: "9854",
    customer_id: "87832",
    customer_name: "Luke Parkin",
    order_date: "2024-01-16T12:40:00",
    order_total: "₹334.50",
    current_order_status: "SHIPPED",
    shipment_address: "Mumbai, Maharashtra, India",
  },
  {
    id: "4",
    product_id: "8763",
    customer_id: "09832",
    customer_name: "Anthony Fry",
    order_date: "2024-02-14T03:24:00",
    order_total: "₹876.00",
    current_order_status: "OUT_FOR_DELIVERY",
    shipment_address: "Mumbai, Maharashtra, India",
  },
  {
    id: "5",
    product_id: "5627",
    customer_id: "97632",
    customer_name: "Ryan Carroll",
    order_date: "2024-02-14T05:24:00",
    order_total: "₹96.35",
    current_order_status: "DELIVERED",
    shipment_address: "Delhi, India",
  },
];


export const popularProducts = [
  {
    id: "3432",
    product_name: 'Macbook M1 Pro 14"',
    product_thumbnail: "https://source.unsplash.com/100x100?macbook",
    product_price: "₹1499.00",
    product_stock: 341,
  },
  {
    id: "7633",
    product_name: "Samsung Galaxy Buds 2",
    product_thumbnail: "https://source.unsplash.com/100x100?earbuds",
    product_price: "₹399.00",
    product_stock: 24,
  },
  {
    id: "6534",
    product_name: "Asus Zenbook Pro",
    product_thumbnail: "https://source.unsplash.com/100x100?laptop",
    product_price: "₹899.00",
    product_stock: 56,
  },
  {
    id: "9234",
    product_name: "LG Flex Canvas",
    product_thumbnail: "https://source.unsplash.com/100x100?smartphone",
    product_price: "₹499.00",
    product_stock: 98,
  },
  {
    id: "4314",
    product_name: "Apple Magic Touchpad",
    product_thumbnail: "https://source.unsplash.com/100x100?touchpad",
    product_price: "₹699.00",
    product_stock: 0,
  },
  {
    id: "4342",
    product_name: "Nothing Earbuds One",
    product_thumbnail: "https://source.unsplash.com/100x100?earphone",
    product_price: "₹399.00",
    product_stock: 453,
  },
];


export const PRODUCTS_DATA = [
  {
    id: 1,
    name: "iPhone 13",
    category: "Smartphone",
    price: 999,
    stockQuantity: 50,
    description: "Latest iPhone model",
  },
  {
    id: 2,
    name: "Samsung Galaxy S21",
    category: "Smartphone",
    price: 899,
    stockQuantity: 40,
    description: "Flagship Samsung smartphone",
  },
  {
    id: 3,
    name: "Google Pixel 6",
    category: "Smartphone",
    price: 799,
    stockQuantity: 30,
    description: "Google's flagship smartphone",
  },
  {
    id: 4,
    name: "OnePlus 9 Pro",
    category: "Smartphone",
    price: 899,
    stockQuantity: 35,
    description: "High-end OnePlus smartphone",
  },
  {
    id: 5,
    name: "Xiaomi Mi 11",
    category: "Smartphone",
    price: 699,
    stockQuantity: 60,
    description: "Affordable flagship from Xiaomi",
  },
  {
    id: 6,
    name: "Sony Xperia 1 III",
    category: "Smartphone",
    price: 1199,
    stockQuantity: 25,
    description: "Premium Sony smartphone with 4K display",
  },
  {
    id: 7,
    name: "Huawei P50 Pro",
    category: "Smartphone",
    price: 1099,
    stockQuantity: 20,
    description: "High-quality camera smartphone from Huawei",
  },
  {
    id: 8,
    name: "Motorola Edge+",
    category: "Smartphone",
    price: 799,
    stockQuantity: 45,
    description: "Motorola's flagship smartphone",
  },
  {
    id: 9,
    name: "LG Velvet",
    category: "Smartphone",
    price: 599,
    stockQuantity: 55,
    description: "Stylish and sleek smartphone from LG",
  },
  {
    id: 10,
    name: "Asus ROG Phone 5",
    category: "Smartphone",
    price: 999,
    stockQuantity: 15,
    description: "Gaming-centric smartphone with high-refresh-rate display",
  },
  {
    id: 11,
    name: "MacBook Pro",
    category: "Laptop",
    price: 1599,
    stockQuantity: 30,
    description: "High-performance MacBook for professionals",
  },
  {
    id: 12,
    name: "Dell XPS 13",
    category: "Laptop",
    price: 1299,
    stockQuantity: 25,
    description: "Premium ultrabook with InfinityEdge display",
  },
  {
    id: 13,
    name: "HP Spectre x360",
    category: "Laptop",
    price: 1399,
    stockQuantity: 20,
    description: "Versatile 2-in-1 laptop with a sleek design",
  },
  {
    id: 14,
    name: "iPad Pro",
    category: "Tablet",
    price: 799,
    stockQuantity: 35,
    description: "Powerful iPad for creative professionals",
  },
  {
    id: 15,
    name: "Samsung Galaxy Tab S7",
    category: "Tablet",
    price: 649,
    stockQuantity: 40,
    description: "Android tablet with high-refresh-rate display",
  },
];


export const ORDERS_DATA = [
  {
    id: "#1",
    productId: "#4324",
    customerName: "Shirley A. Lape",
    orderDate: "17 February 2024",
    orderTotal: "₹32,500.00",
    shippingAddress: "Mumbai, Maharashtra, India",
    orderStatus: "placed",
  },
  {
    id: "#2",
    productId: "#5678",
    customerName: "John Doe",
    orderDate: "19 January 2024",
    orderTotal: "₹24,000.00",
    shippingAddress: "Bangalore, Karnataka, India",
    orderStatus: "confirmed",
  },
  {
    id: "#3",
    productId: "#9876",
    customerName: "Alice Smith",
    orderDate: "12 March 2024",
    orderTotal: "₹41,925.75",
    shippingAddress: "Delhi, India",
    orderStatus: "shipped",
  },
  {
    id: "#4",
    productId: "#1234",
    customerName: "Bob Johnson",
    orderDate: "24 February 2024",
    orderTotal: "₹21,275.30",
    shippingAddress: "Jaipur, Rajasthan, India",
    orderStatus: "out_for_delivery",
  },
  {
    id: "#5",
    productId: "#2468",
    customerName: "Emily Wilson",
    orderDate: "8 March 2024",
    orderTotal: "₹30,000.00",
    shippingAddress: "Chandigarh, India",
    orderStatus: "delivered",
  },
  {
    id: "#6",
    productId: "#1357",
    customerName: "Michael Brown",
    orderDate: "5 January 2024",
    orderTotal: "₹15,225.50",
    shippingAddress: "Pune, Maharashtra, India",
    orderStatus: "placed",
  },
  {
    id: "#7",
    productId: "#7890",
    customerName: "Jessica Lee",
    orderDate: "11 March 2024",
    orderTotal: "₹60,750.00",
    shippingAddress: "Kolkata, West Bengal, India",
    orderStatus: "confirmed",
  },
  {
    id: "#8",
    productId: "#5432",
    customerName: "David Wilson",
    orderDate: "22 February 2024",
    orderTotal: "₹32,580.80",
    shippingAddress: "Lucknow, Uttar Pradesh, India",
    orderStatus: "shipped",
  },
  {
    id: "#9",
    productId: "#9876",
    customerName: "Jennifer Davis",
    orderDate: "14 January 2024",
    orderTotal: "₹28,025.25",
    shippingAddress: "Bhopal, Madhya Pradesh, India",
    orderStatus: "out_for_delivery",
  },
  {
    id: "#10",
    productId: "#1357",
    customerName: "Daniel Miller",
    orderDate: "18 March 2024",
    orderTotal: "₹61,000.00",
    shippingAddress: "Nagpur, Maharashtra, India",
    orderStatus: "delivered",
  },
  {
    id: "#11",
    productId: "#2468",
    customerName: "Sarah Johnson",
    orderDate: "2 January 2024",
    orderTotal: "₹50,000.00",
    shippingAddress: "Indore, Madhya Pradesh, India",
    orderStatus: "placed",
  },
  {
    id: "#12",
    productId: "#7890",
    customerName: "James Smith",
    orderDate: "9 March 2024",
    orderTotal: "₹72,050.50",
    shippingAddress: "Kanpur, Uttar Pradesh, India",
    orderStatus: "confirmed",
  },
  {
    id: "#13",
    productId: "#1234",
    customerName: "Emma Davis",
    orderDate: "16 February 2024",
    orderTotal: "₹45,075.75",
    shippingAddress: "Amritsar, Punjab, India",
    orderStatus: "shipped",
  },
  {
    id: "#14",
    productId: "#4324",
    customerName: "Chris Wilson",
    orderDate: "20 January 2024",
    orderTotal: "₹30,025.25",
    shippingAddress: "Ahmedabad, Gujarat, India",
    orderStatus: "out_for_delivery",
  },
  {
    id: "#15",
    productId: "#5678",
    customerName: "Laura Taylor",
    orderDate: "25 February 2024",
    orderTotal: "₹60,000.00",
    shippingAddress: "Hyderabad, Telangana, India",
    orderStatus: "delivered",
  },
];
